DROP TABLE MEMBERS;
DROP TABLE BOARDS;

-- 회원 테이블 : MEMBER
CREATE TABLE MEMBER
(
	NO NUMBER,                            -- PK : 회원 순서
	ID VARCHAR2(32) NOT NULL UNIQUE,      -- 아이디
	PW VARCHAR2(32) NOT NULL,             -- 비밀번호
	NAME VARCHAR2(50),                    -- 이름
	EMAIL VARCHAR2(200) NOT NULL UNIQUE,  -- 이메일
	REGDATE DATE                          -- 가입일자
);

-- 게시글 테이블 : BOARD
CREATE TABLE BOARD
(
	IDX NUMBER,                      -- PK : 게시글 순번
	AUTHOR VARCHAR2(50),             -- FK : 작성자 (MEMBER_ID :: references)
	TITLE VARCHAR2(2000) NOT NULL,   -- 타이틀
	CONTENT VARCHAR2(4000),          -- 글내용
	HIT NUMBER,                      -- 조회수
	POSTDATE DATE                    -- 작성일자
);


-- 기본키
ALTER TABLE MEMBER ADD CONSTRAINT MEMEBER_PK PRIMARY KEY (NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(IDX);
-- 외래키
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY(AUTHOR) REFERENCES MEMBER(ID); 


-- 시퀀스
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

select * from member;


